package constants

const (
	USER_NAME_MAP           = "USERNAME"
	PASSWORD                = "PASSWORD"
	SOFTWARE_TOKEN_MFA_CODE = "SOFTWARE_TOKEN_MFA_CODE"
	SECRET_HASH             = "SECRET_HASH"
	USER_PASSWORD_AUTH_FLOW = "USER_PASSWORD_AUTH"
)

const (
	USER_ATTRIBUTE_NAME       = "name"
	USER_ATTRIBUTE_EMAIL      = "email"
	USER_ATTRIBUTE_LOCALE     = "locale"
	USER_ATTRIBUTE_UPDATED_AT = "updated_at"
	USER_ATTRIBUTE_ES_CO      = "es_CO"
)
